### ISSUE TITLE
Silent Ubuntu version switch in deployed images

### ISSUE THREAD

**Issue by cheffe112** [osrf/docker_images#104]
A couple days ago, the libgazebo7 container (and dependent ones) was silently switched to Ubuntu Xenial from Trusty in commit 06580e3b550b5ef54bda4abc65246d98e76aed48 @ruffsl.
This broke the whole setup which is used in a multi-partner EU project and our partners went berserk because they weren't able to build anything anymore due to dependency issues.

I'd propose to refrain from switching Ubuntu versions in known containers, instead create some libgazebo7-xenial overlay or something. Breaking the "dependency API" generally sounds like a bad idea to me.

**Comment by ruffsl** [comment]
This migration and rational was ticketed before here: https://github.com/osrf/docker_images/issues/92
And generally announced for feedback to the official gazebo community before merging: 
https://community.gazebosim.org/t/migrating-gazebo-7-docker-tags-to-xenial-base-image/27/1

The justification being that the Gazebo7 tags were being built from a base image that would have reached EOL before Gazebo7's own EOL date. So the default `libgazebo7` tag needed to be corrected eventually before trusty builds ceased on dockerhub in order to continue support for Gazebo7 over its release cycle.

Apologies for breaking any Dockerfiles in the quest to fix others https://github.com/osrf/docker_images/issues/84 . I've been able to avoid changing base dependencies for all our ros tag migrations, but was unable to do so in this case due to the conflicting EOL between Trusty and Gazebo7. That being said we could provide additional os code mane overlay tags for `gazebo` like we do for `ros`, as our refactored docker image repository structure now supports this.

In the short term, you could pull the old version of `libgazebo7` tag before the migration:
```
docker pull gazebo@sha256:<older_libgazebo7_shasha256_here>
```
See here for more details:   
* https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier
* https://stackoverflow.com/questions/47066021/how-to-get-a-list-of-immutable-identifier-digest-from-a-docker-image
* https://stackoverflow.com/questions/41808763/how-to-determine-the-docker-image-id-for-a-tag-via-docker-hub-api
* https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md

In the long term, perhaps we can create a dedicated category on gazebo community's discourse to broadcast maintenance announcements that users can monitor.

**Comment by ruffsl** [comment]
Another alternative if your require custom dependencies would be to fork the current images and adjust the `FROM` field in the relevant Dockerfile to point to whatever image you need, then connect it to an automated Docker Hub repo for your own organization.

We have a [number of users](https://github.com/osrf/docker_images/network/members) who do just that to easily build ROS or Gazebo images with cuda libraries pre installed for [nvidia-docker](https://github.com/NVIDIA/nvidia-docker), custom OpenCV builds, or provide alteritive keyservers/proxies setings to build the Dockerfiles from behine corpate firewalls.

One caveat though is only the official library repos seem to properly handle nested tag builds within a single repo, as its dedicated [build scaffolding](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gazebo/) differs from a traditional docker hub automated docker repo.

**Comment by cheffe112** [comment]
Thanks for the detailed explanation. However, we've dumped the Gazebo images meanwhile and now use the ROS Trusty images while manually installing Gazebo afterwards in the Dockerfiles. Setting up Docker Hub is too much additional work although I have to admit that this is probably the cleanest way.
