### ISSUE TITLE
Why do the Dockerfiles stipulate specific version numbers?

### ISSUE THREAD

**Issue by lag-linaro** [osrf/docker_images#171]
At the moment, version numbers for varying architectures are not in sync.

Taking Gazebo8 and Xenial as an example, ARM64 and ARMHF are currently on 8.0.0 and AMD64 and I386 are on 8.6.0.  The Dockerfile for this combination stipulates 8.6.0, ensuring breakage when attempting to build images for architectures which should otherwise be supported.

**Comment by mikaelarguedas** [comment]
thanks @lag-linaro for pointing this out.
The reason we pin the versions down is to ensure the images are rebuilt when a new version comes out (otherwise the cache is not busted and the images are not up to date).

The initial logic was developped for ROS packages where the versions are always in sync, and you are totally right, this doesnt apply to Gazebo and the logic should be changed to cover that case.

This seem like another good use case for either specifying exact version numbers on a per architecture basis (https://github.com/osrf/docker_images/issues/112) or maintaining separate dockefiles per architecture (https://github.com/osrf/docker_images/pull/115)

@ruffsl FYI

**Comment by ruffsl** [comment]
As @mikaelarguedas duly pointed out, this ensures we always have a reliable mechanism for breaking the build cache when bumping up the version. It also affords us a degree of repeatability and regulation of the exact release that goes into the official images, and thus a cautionary procedure we abide by:  
https://github.com/docker-library/official-images#repeatability


Now that Docker Hub official libraries support multiarch:  
https://github.com/docker-library/official-images#multiple-architectures

Its doable to extend gazebo image builds for more than just amd64. When I first ported the ROS1 images to multiarch I briefly thought about doing the same for gazebo as well, but wasn't sure if there would be any user demand to justify the extension.

@lag-linaro , may I inquire you use case or applications that necessitating containerised gazebo on arm?

**Comment by lag-linaro** [comment]
@mikaelarguedas, @ruffsl, thank you for taking the time to explain why you pin exact versions to builds in your Dockerfile and for being receptive to multi-arch builds.

@ruffsl in answer to your question, I'm afraid I do not have anything exciting to tell you.  As an integrator and ARM64v8 advocate/evangelist, I'm seeking to ensure that as many useful Docker Hub based projects are accessible to users of the latest hardware to be operated on the desktop and in the data centre.  Essentially I am just the middleman. :smile:

**Comment by ruffsl** [comment]
Tracking arm support for gazebo here: https://github.com/osrf/docker_images/issues/173
