### ISSUE TITLE
Use of ROS_DISTRO vs ROS2_DISTRO in ROS2 images

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#187]
In the current dockerfiles [`ROS_DISTRO`](https://github.com/osrf/docker_images/blob/b5dbb565f7ebd92dfd1d85aa8c0be6e657979b7b/ros/melodic/ubuntu/bionic/ros-core/Dockerfile#L39) is set as an environmental variable to offer users a quick means of alasing the version of ROS installed in the container image. Sometime around creating the dockerfiles for ROS2, I introduced the use of [`ROS2_DISTRO`](https://github.com/osrf/docker_images/blob/b5dbb565f7ebd92dfd1d85aa8c0be6e657979b7b/ros2/bouncy/ubuntu/bionic/ros-core/Dockerfile#L34-L35) to distinguish target distro of ROS that where installed.

However, `ROS2_DISTRO` does not seem to be adopted anywhere else in ROS2, given sourcing ROS2 setup.sh merely retains the use of `ROS_DISTRO` to denote the distro configured, regardless of being ROS1 or ROS2. Rather than setting `ROS2_DISTRO`, perhaps it would be prudent to rely on `ROS_DISTRO` in the ROS2 images for consistency.

I mention this as I wasn't sure if there was ever any intention of rectifying the used of ROS1 and ROS2 in the same shell environment, thus necessitating some variable schema for the two to coincide, or that the ros1/ros2 would have mutually exclusive environments.

**Comment by mikaelarguedas** [comment]
I'll try to give a more complete response tomight or tomorrow. In the meantime if it's useful I started work in that direction a few months back on this branch: https://github.com/osrf/docker_templates/tree/homogenize_ROS_DISTRO

**Comment by mikaelarguedas** [comment]
Our preference is to use the same set of variables across distributions so that the tool scan work with ROS 2 distributions without modification. (We do now provide a ROS_VERSION variable to be able to tell if using ROS1 or ROS 2).

The only scenarios we see where there is a need to have 2 distributions sourced (ROS 1 and ROS 2) are in the case of the ros1_bridge. Any other shell should have a single distro sourced to avoid collision or unexpected libraries and include being picked up based on sourcing order.

As far as docker images are concerned. I'm thinking of creating an image template specifically for the ros1_bridge image. And that image will be the only one with knowledge of 2 distros (apt repo of both ROS1 and ROS2 , a ROS1_DISTRO eng bar and an entry point sourcing both distros)

**Comment by mikaelarguedas** [comment]
With https://github.com/osrf/docker_templates/pull/43 and https://github.com/osrf/docker_images/pull/190 merged this can now be closed
