### ISSUE TITLE
Can we get a ros2:latest dockerfile?

### ISSUE THREAD

**Issue by mkhansen-intel** [osrf/docker_images#201]
We're trying to use Travis CI to test our Navigation code, and when building from source it takes too long (> 50 minutes) to build ROS2. We've been using the ros2:bouncy-desktop tagged docker image, but we'd like to move to using the master branch (or equivalent) for our development and testing. I wanted to know if there's a daily build (or at least weekly) that could generate a ros2:latest docker image for us to pull and use in our testing. That would really help.

**Comment by sloretz** [comment]
I don't think there is a nightly docker image, but there are nightly packaging jobs. They create an archive with a ROS 2 workspace that could be used as an underlay for your CI

https://ci.ros2.org/view/packaging/

For a linux job
```bash
wget https://ci.ros2.org/view/packaging/job/packaging_linux/lastSuccessfulBuild/artifact/ws/ros2-package-linux-x86_64.tar.bz2
tar -xjvf ros2-package-linux-x86_64.tar.bz2
. ros2-linux/setup.bash
# Now build other stuff on top
```

**Comment by mkhansen-intel** [comment]
I'll give this a try! Thanks @sloretz

**Comment by mkhansen-intel** [comment]
OK, this works. However, it still would be nicer if the nightly build also generated a Docker image like the ones being generated by this repo. Maybe a future enhancement? :) @ruffsl - is that something you would know how to do?

**Comment by ruffsl** [comment]
@mkhansen-intel , to be clear, between the title of this issue vs what your requesting. are you asking for:
* A added ROS2 Dockerfile that builds the latest master branches of ROS2 from source
* Additionally, host a nightly derived Docker image using a automated repo on Docker Hub

Having an automated repo build the master branch of ROS2 from source wouldn't be hard, given we already have the Dockerfile scaffolding for creating one that builds the latest stable release from source:

https://github.com/osrf/docker_images/blob/55f03de3a06991c28a897982652dbafcb09d5592/ros2/source/source/Dockerfile#L66-L67

However, as per @sloretz mentioned, there seem to be some nice readily available nightly builds from https://ci.ros2.org/view/packaging, so I would be inclined to rely on those, rather than force Travis or Docker Hup to duplicate the same workload.

That being said, I still think there would be some value in wrapping such nightly builds into a Docker image hosted from an automated repo on Docker Hub, i.e. have those same nightly builds also trigger a webhook under our ros2 docker hub repo to build an image that installs and sets up those binaries. Then other users could just point there derived automated repos to trigger of that, etc.

I'll start a PR for the Docker image, but I'll need some assistance from someone else with org permissions to created the webhook and embed the callback in the nightly build job on ci.ros2.org to trigger it event based.

also pinging @tfoote @nuclearsandwich

**Comment by ruffsl** [comment]
With the referenced PRs above merged and nightly tag now live, I think we can finally close this.
