### ISSUE TITLE
Docker images missing from Dockerhub

### ISSUE THREAD

**Issue by jpsamper2009** [osrf/docker_images#232]
I tried to pull the `osrf/ros2:crystal-desktop` image this morning, and it looks like it has gone missing from Dockerhub (https://hub.docker.com/r/osrf/ros2/tags). Is this on purpose? Is there a plan to bring them back?

**Comment by jpsamper2009** [comment]
It look like they have moved to `osrf/ros`: https://hub.docker.com/r/osrf/ros/tags

**Comment by sloretz** [comment]
> It look like they have moved to `osrf/ros`: https://hub.docker.com/r/osrf/ros/tags

Correct, all ros 2 tags are at [osrf/ros](https://hub.docker.com/r/osrf/ros/), and won't be returning to `osrf/ros2`. This matches the official docker images at [ros](https://hub.docker.com/_/ros). For more context, see https://github.com/docker-library/docs/pull/1381#issuecomment-447380202 and the comments after. I'll close this since the question appears to be answered.
