### ISSUE TITLE
ROS2 version mismatch crystal

### ISSUE THREAD

**Issue by lodevdl** [osrf/docker_images#260]
Could it be that if I pull the docker and use it (nightly), you define version crystal and use the latest ci build version on the master branch? If I try to build the examples git and checkout the crystal branch I get a lot of compilation mistakes. On the other hand if I use the master branch of the examples repository everything compiles fine? Thank you already for the work being done.

**Comment by mikaelarguedas** [comment]
Yes it is the case.

The goal of the `osrl/ros2:nightly` image is to provide a build of the `master` branch on a daily basis.
If you want to use ROS crystal instead of the nightly build, the appropriate image is `ros:crystal` (or `osrf/ros:crystal-desktop` if you want the gui tools as well). If you use the `osrf/ros2:nightly` image, you should use the default/master branch for all the repositories.

As of why is the `ROS_DISTRO` environment variable defined to `crystal` in the nightly image, there are a couple technical reasons, from the top of my head, we need to install the `ros-crystal-ros-workspace` package via apt, I think there are other reasons as well. 

As soon as the `ros-dashing-ros-workspace` is available on the main apt repository we will be able to update this to point to `dashing`, currently it's still only available in the [testing repository](http://repo.ros2.org/status_page/ros_dashing_default.html?q=ros_workspace).
