### ISSUE TITLE
colcon not found

### ISSUE THREAD

**Issue by ipa-hsd** [osrf/docker_images#262]
I have the following `Dockerfile`:

```
from osrf/ros:crystal-ros1-bridge

RUN apt-get update
RUN mkdir -p /ros2_ws/src/ \
    && cd /ros2_ws/ \
    && colcon build
```
When I try to build the image, I get the error:
```
/bin/sh: 1: colcon: not found
```
The `Dockerfile` as per https://hub.docker.com/_/ros/ for `ros:crystal-ros-core-bionic` is [this](https://github.com/osrf/docker_images/blob/bfad8a41952cd552904d4644a1c5c2d22396644d/ros/crystal/ubuntu/bionic/ros-core/Dockerfile). `python3-colcon-common-extensions` is missing in this file. But the latest [Dockerfile](https://github.com/osrf/docker_images/blob/master/ros/crystal/ubuntu/bionic/ros-core/Dockerfile) includes it. Even though as per https://hub.docker.com/r/osrf/ros/tags, the last image was updated "12 days ago", it seems to be using quite an old `Dockerfile`. 

Shouldn't it be using the latest version to update the images?

**Comment by ruffsl** [comment]
Thanks for spotting the discrepancy. It turns out that the upstream library was out of sync and missing the added template changes that installs colcon as a bootstrap dependency. I had misthought its author had opened an upstream PR. https://github.com/osrf/docker_images/pull/244

I've opened up the upstream PR that will bring them back in sync.
https://github.com/docker-library/official-images/pull/5961

**Comment by ruffsl** [comment]
The respective PR has been merged, and I've triggered osrf/ros2 to rebuild those images.
Feel free to re-open if still unresolved.
