### ISSUE TITLE
Why processes run as root inside ros docker container?

### ISSUE THREAD

**Issue by smihael** [osrf/docker_images#287]
At https://hub.docker.com/_/ros it is stated that "by default, the container runs as the root user". Why? Wouldn't it be better to run processes in the containers with minimalneeded permissions (see also https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)

**Comment by sloretz** [comment]
They run as root because that's the default user when starting from an Ubuntu docker image. It is possible to add a user to avoid running as root.

```Dockerfile
FROM ros:melodic-robot

ENV USERNAME developer
RUN useradd -U -ms /bin/bash $USERNAME \
 && echo "$USERNAME:$USERNAME" | chpasswd

USER $USERNAME
```

Why not add a user to the base image? Sometimes someone wants a user with a user id with the same id as their username outside the container. This allows mounting docker volumes and editing files inside and outside the container without changing their ownership.

```Dockerfile
FROM ros:melodic-robot

# Add a user with the same user_id as the user outside the container
# Requires a docker build argument `user_id`
ARG user_id
ENV USERNAME developer
RUN useradd -U --uid ${user_id} -ms /bin/bash $USERNAME \
 && echo "$USERNAME:$USERNAME" | chpasswd

USER $USERNAME
```

**Comment by ruffsl** [comment]
As mentioned by @sloretz , we don't add or change the default user given that they serve as a base image for a wide number of configurations and customizations for downstream users. We instead try to minimize the number of alterations to the parent images we build from when installing and configuring added environments as to be as transparent, so that they may be easily interchangeable. Changing the default user is usually left to the developer to decide for their own application.

For example, if we changed the default user in `ros:indigo-ros-core` here, then an end user wishing to swap the base image for their deep learning project Dockerfile from `ubuntu:trusty` to `ros:indigo-ros-core` to include a ros install would have to modify their Dockerfiles and scripts to install and use `sudo` or change the user back and forth from root when adding packages, rather than simply updating `FROM`.
