### ISSUE TITLE
osrf/ros2:nightly image seems to contain Dashing instead of master

### ISSUE THREAD

**Issue by crdelsey** [osrf/docker_images#304]
I'm getting an error when building the nav2 docker image 
```
--- stderr: nav2_costmap_2d
/opt/nav2_ws/src/navigation2/nav2_costmap_2d/src/costmap_2d_ros.cpp:49:10: fatal error: tf2_ros/create_timer_ros.h: No such file or directory
#include "tf2_ros/create_timer_ros.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
You can see an example build here. (https://cloud.docker.com/u/rosplanning/repository/registry-1.docker.io/rosplanning/navigation2/builds/08925ac5-f815-4c2c-af23-0d936a7152d4)

This file is definitely missing from the `osrf/ros2:nightly` image, but it is present in the nightly tarball.The files in the docker image look more like the ros2 dashing branch, rather than master.

**Comment by mikaelarguedas** [comment]
Thanks @crdelsey for pointing this out. I believe the packaging job has been used to generate the Dashing patch 2 archive and caused the nightly image to be rebuilt with that archive. @nuclearsandwich FYI.

I triggered a manual rebuild of the image, but it currently fails to build due to misdeclared dependencies in the latest nightly archive.

**Comment by nuclearsandwich** [comment]
Apologies for setting this one up. I don't like using the ci_packaging jobs for release builds but that vague dislike will have to yield to avoiding this problem in the future.

**Comment by mikaelarguedas** [comment]
FIx to `rosidl_actions_py` has been merged and the archive rebuilt.

Build is failing because another package introduced a non existing rosdep key: https://github.com/eProsima/foonathan_memory_vendor/pull/9.

@nuclearsandwich Do you think this can get merged shortly or does it make sens to open a PR on ros2/ros2.repos so that the next nightly image builds successfully?

**Comment by mikaelarguedas** [comment]
`ros2:nightly` has been rebuilt using https://github.com/osrf/docker_images/commit/3331ef6f9b2357a6e3478f9c14c7a68a1a48f04d and contains the content of master and not dashing

**Comment by ruffsl** [comment]
Two questions:
 * Where in the image filesystem can I look as to determine which kind of build was installed?
 * Could we add a check to the nightly Dockerfile fail the Dockerhub build if something else is downloaded? Or is there a less generic url we could target other than `lastSuccessfulBuild`.  

https://github.com/osrf/docker_images/blob/cb5ee27800405d1aac40982540c3f661b80e94f7/ros2/nightly/nightly/Dockerfile#L63-L65

**Comment by mikaelarguedas** [comment]
> Where in the image filesystem can I look as to determine which kind of build was installed?

I'm not aware of any way of knowing so from the archive content

> Could we add a check to the nightly Dockerfile fail the Dockerhub build if something else is downloaded? Or is there a less generic url we could target other than lastSuccessfulBuild.

The logic of this image is that the nightly-triggered packaging job would be ran only for nightly master builds.
The `lastSuccessfulBuild` is both great and unfortunate in the sense that it allows a non-changing URL tracking new build artifacts and not letting you shoot yourself in the foot trying to pull a non-existent or corrupted archive. But doesn't differentiate on any parameter like "was this job a nightly build".

---

Possible solutions:
- If the logic of triggering the Docker builds was part of ci.ros2.org, we could somehow work around the issue as Jenkins could check things like "was this build triggered on a timer or manually" or "was it using default parameters corresponding to a master build" and trigger the webhook only in these scenarios.
- It may be possible to do the same logic from travis but it seems somehow wrong as whatever the heuristic relies on behavior of ci.ros2.org that could change at any time, so having the heuristic close to the parameter definition seem to make more sense.
In both case this seems fragile and code to maintain that could likely fall out of sync.

- Maybe the simplest solution is the right one and we could see if OSRF is ok having a dedicated "nightly_packaging_<platform>" job that will only build master on a daily basis. Or dedicate the current "packaging_<platform>" jobs to that effect.

**Comment by mikaelarguedas** [comment]
> ros2:nightly has been rebuilt using 3331ef6 and contains the content of master and not dashing

or almost, the archive does contain master, but the docker image ends up installing most of dashing because of the 2 following issues:
- `action_tutorials` is not available in the nightly archive but still declared as a dep by some packages: https://github.com/ros2/ros2cli/pull/310
- sqlite3_vendor doesnt install it's package.xml

**Comment by ruffsl** [comment]
I think we could mark all packages with the `ros-$ROS_DISTRO` with `Pin-Priority: -1` or as hold to help ensure the Dockerfile fails to build when such packages try to sneak in, rather than silently over-installing the released distro packages over the installed nightly archive.

* https://askubuntu.com/questions/75895/how-to-forbid-a-specific-package-to-be-installed
* https://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package

**Comment by mikaelarguedas** [comment]
oh interesting, I didnt know about that option, I used a slightly different approach today to find the packages having issues https://github.com/osrf/docker_templates/commit/9aa7196427e589e6add73ab271b3b2d0b805be87

**Comment by mikaelarguedas** [comment]
Nightly image is now fixed and CI jobs using it started passing again :tada:  (e.g. https://travis-ci.org/Karsten1987/confbot_robot)
Safeguards have been added so that the image fails to build if any dependency on a ROS package is not satisfied (instead of satisfying them by installing ros-dashing-... debs). Users of this image will also be prevented from installing ros dashing debs via rosdep.

Automated builds have been switched back to the master branch.

Closing this, @crdelsey feel free to comment here or open a new issue if you encounter problems with the newly built images

**Comment by crdelsey** [comment]
@mikaelarguedas  Awesome! Thanks for fixing this so quickly. It looks good on my end.
