### ISSUE TITLE
ROS2 nightly images do not include rmw_cyclonedds_cpp

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#324]
It doesn't seem that `rmw_cyclone_cpp` is being included in the `osrf/ros2:nightly-rmw` tag, given that the package itself is absent from the nightly fat archive installed to begin with. This package seems to have been released into dashing, so is there a reason for its omission from the nightly archive?
cc @tfoote @nuclearsandwich

**Comment by nuclearsandwich** [comment]
> so is there a reason for its omission from the nightly archive?

It isn't part of the main ros2.repos file which is what determines the contents of the nightly archive. It looks like there's already activity making that happen in https://github.com/ros2/ros2/issues/786 but in point of fact, a package being released into Dashing does not mean it is officially supported. Only RMWs specified in [REP-2000](https://www.ros.org/reps/rep-2000.html) are supported at their listed support tiers. Since CycloneDDS is unlisted it is implicitly tier 3, community supported.

**Comment by mikaelarguedas** [comment]
nightly images now include `rmw_cycloneds_cpp`
