### ISSUE TITLE
OpenSplice should be removed from Foxy images

### ISSUE THREAD

**Issue by dirk-thomas** [osrf/docker_images#379]
Since it is officially not supported in Foxy.

**Comment by mikaelarguedas** [comment]
Thanks for the headsup

There are currently no Foxy images.
The Foxy images once released will simply install "ros-foxy-ros-core". So it will come only with whatever the default RMW implementation is.

The `osrf/ros2:nightly` images track the state of the nightly archive. So they came without `rmw_opensplice` and related packages since https://github.com/ros2/ros2/pull/865

As far as I can tell there is no action item associated with this, I'm going to close this.

@dirk-thomas feel free to re-open if I misunderstood your comment and there is an action item associated with this issue

**Comment by dirk-thomas** [comment]
I though there are Docker images tracking the current nightly builds from master (which is essentially Foxy).

**Comment by dirk-thomas** [comment]
E.g. this would be obsolete: https://github.com/osrf/docker_images/blob/58f2e8a1d7bcf64cbe7ff0de936d58d4130eb918/ros2/nightly/nightly/Dockerfile#L99

**Comment by mikaelarguedas** [comment]
> I though there are Docker images tracking the current nightly builds from master (which is essentially Foxy).

Yes the `ros2:nightly` docker image tracks the nightly builds of ci.ros2.org. But those builds did not include any Opensplice related packages since more than a month AFAICT.
Does https://github.com/ros2/ci/pull/401 impact the content of the nightly archive?


> E.g. this would be obsolete: 

Yeah I went back and forth on this one. If people pass a specific [ROS2_BINARY_URL](https://github.com/osrf/docker_images/blob/58f2e8a1d7bcf64cbe7ff0de936d58d4130eb918/ros2/nightly/nightly/Dockerfile#L64) they might still need it. 
Similarly to the source image [still skipping the `libopensplice67`](https://github.com/osrf/docker_images/blob/58f2e8a1d7bcf64cbe7ff0de936d58d4130eb918/ros2/source/images.yaml.em#L50) even if the last distro used `libopensplice69`

But there is a bigger question with this is that now we have `ros2:nightly` and `ros2:nightly-rmw` that are the same because the archive now ship with both fully fledged FastRTPS and CycloneDDS.
I opened https://github.com/osrf/docker_images/issues/380 to track those down

**Comment by dirk-thomas** [comment]
> Does ros2/ci#401 impact the content of the nightly archive?

Probably not since the OpenSplice repo had already been removed for over a month.

> If people pass a specific ROS2_BINARY_URL they might still need it.

`rmw_opensplice_cpp` won't build in Foxy and there is no `libopensplice69` Debian package for Focal.

**Comment by mikaelarguedas** [comment]
> rmw_opensplice_cpp won't build in Foxy 

My point was that people can pass past archive URL and it should still work. They could pass the Dashing patch release URL.

But that raises a good point: ci.ros2.org is now building against `focal`. The nightly images here are still based on `bionic`.
So if they are updated to build on focal, we can remove any legacy keys or else :+1:
Thanks for pointing it out

**Comment by dirk-thomas** [comment]
> My point was that people can pass past archive URL and it should still work. They could pass the Dashing patch release URL.

Sure, Dashing and Eloquent should still continue to work.

> But that raises a good point: ci.ros2.org is now building against `focal`.

Not yet - but will be in the very near future. The ROS Foxy jobs on build.ros2.org already build on Ubuntu Focal.

**Comment by mikaelarguedas** [comment]
> Not yet - but will be in the very near future. The ROS Foxy jobs on build.ros2.org already built on Ubuntu Focal.

haha I should have checked :confounded:
Is it possible to get notified when that switch happen ? (an issue to watch ?) this way we can make sure to update in a timely manner

**Comment by dirk-thomas** [comment]
I will ping you on this ticket - there is no other ticket atm afaik.
