### ISSUE TITLE
arm64 for osrf/ros:eloquent-desktop

### ISSUE THREAD

**Issue by sshmaxime** [osrf/docker_images#425]
Can we have an arm64 image for osrf/ros:eloquent-desktop ?

**Comment by ruffsl** [comment]
Automated repos on Docker Hub only have build workers for amd64, official library repos being the exception:

* https://github.com/docker/hub-feedback/issues/1874

We could try and extend the manifest list to enable a multi-arch docker registry for the `osrf/ros` repo:

* https://hub.docker.com/r/ckulka/multi-arch-example
* https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/deploying-multi-architecture-docker-registry

We could then and build and push tag from CI jobs instead of using Docker Hub's automated builds, like from our CI, and used qemu to build the arm images. However, we'd also need to extend our github actions CI. cc @mikaelarguedas
