### ISSUE TITLE
foxy-desktop: rviz2 errors not finding shared libraries

### ISSUE THREAD

**Issue by russkel** [osrf/docker_images#460]
Seems to be something up with the image:

```
$ docker run --rm -it osrf/ros:foxy-desktop
root@85599ff73d47:/# rviz2
rviz2: error while loading shared libraries: libconsole_bridge.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by mikaelarguedas** [comment]
to be able to run rviz2 (or other graphical tools) you need to give X11 access to your container, ideally using nvidia docker too to be able to leverage graphical hardware.

There are many ways of doing so https://answers.ros.org/question/313786/running-ros-and-its-gui-tools-through-a-docker-image/

---

However the library issue you're facing seems unrelated to the graphical environment and is likely due to an rviz2 issue that has been fixed but the foxy image is not up to date (pending https://github.com/docker-library/official-images/pull/8786)

If you run an apt upgrade in your container it should work:

```
$ docker pull osrf/ros:foxy-desktop
$ rocker --x11 osrf/ros:foxy-desktop
# rviz2
rviz2: error while loading shared libraries: libconsole_bridge.so.1.0: cannot open shared object file: No such file or directory
# ldd /opt/ros/foxy/lib/rviz2/rviz2 | grep consol
	libconsole_bridge.so.1.0 => not found
	libconsole_bridge.so.0.5 => /opt/ros/foxy/lib/libconsole_bridge.so.0.5 (0x00007f68c9a61000)
```
If you upgrade:
```
# apt update && apt upgrade -y
# ldd /opt/ros/foxy/lib/rviz2/rviz2 | grep consol
	libconsole_bridge.so.1.0 => /opt/ros/foxy/lib/libconsole_bridge.so.1.0 (0x00007ff4e39c8000)
# rviz2
[INFO] [1601221583.409704360] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [1601221583.409867589] [rviz2]: OpenGl version: 3.1 (GLSL 1.4)
[INFO] [1601221583.450979317] [rviz2]: Stereo is NOT SUPPORTED
```

**Comment by russkel** [comment]
> viz2 issue that has been fixed but the foxy image is not up to date

Great, just wanted to make sure this was a known and reported issue.

Thanks for the solution.
