### ISSUE TITLE
[indigo-ros-core] docker exec returns to host in case of command error

### ISSUE THREAD

**Issue by ThmX** [osrf/docker_images#49]
The `set -e` line in `ros_entrypoint.sh` has the problem to close the connection with the container if an error occurs in bash:
```
hostname@host:~$ docker exec -it ros-indigo bash
root@8c4275643053:/# abcd
bash: abcd: command not found
hostname@host:~$ 
```

**Comment by ruffsl** [comment]
From my experience, this is intentional so that any errors in the PID1 process can be handled appropriately by the use-case that started the containerized process to begin with. This style is seen in the [dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#entrypoint) docs page, as well mentioned here in [Writing Robust Bash Shell Scripts](http://www.davidpashley.com/articles/writing-robust-shell-scripts/#id2382181).

If you'd like to avoid this behavior, such as the container halting whenever you mistype a command in a bash shell running as PID1, you could either use screens, tmux, byobu as PID1 and then your shell in that, or make a new child image that modifies the original [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) or `ros_entrypoint.sh` file.

We could ask the official docker library maintainers if you feel this is no longer the best default behavior, but its just the entrypoint style that was recommended back when [first releasing](https://github.com/docker-library/official-images/pull/751#issuecomment-106960591) the official ros repo images. It looks like it does have its gotchas though: [BashFAQ/105](http://mywiki.wooledge.org/BashFAQ/105)

**Comment by ruffsl** [comment]
Closing for now, but feel free to reopen with suggestions.
