### ISSUE TITLE
Rolling Docker Image Not Updated

### ISSUE THREAD

**Issue by SteveMacenski** [osrf/docker_images#559]
There was a sync on the 6th https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2021-08-06/21737 but the last update in dockerhub was 15 days ago https://hub.docker.com/layers/ros/library/ros/rolling-ros-core/images/sha256-c2f8c1fbe1b3dc3d98c532d7797036db90c409e648e473cc21cfba41bb97c834?context=explore

Needed for PRs in Nav2:
- https://github.com/ros-planning/navigation2/pull/2489
- https://github.com/ros-planning/navigation2/pull/2483

**Comment by mikaelarguedas** [comment]
updates in dockerhub happen only if the base image (ubuntu) is updated or if the packages listed in the image (ros-core, ros-base etc) get a new version released.
As this sync didnt imply any new release of the metapackages the image cannot be updated.
An attempt to fix the issue was made in https://github.com/osrf/docker_templates/pull/90 but was rejected by the docker librarians

**Comment by SteveMacenski** [comment]
Ah ok. Any hope for manual updates when we do syncs or has that already been discussed and passed on?

**Comment by mikaelarguedas** [comment]
> Any hope for manual updates when we do syncs or has that already been discussed and passed on?

So far we didnt find any way to automatically or manually update official images during a sync in a future-proof way while keeping the same dockerfiles for all architectures and not rewriting our entire image generation process.

You can find leads that have been explored in the various PRs and tickets referencing the original issue https://github.com/osrf/docker_images/issues/112
