### ISSUE TITLE
cannot run gazebo9 on docker with privileged on melodic 

### ISSUE THREAD

**Issue by Aetherbase** [osrf/docker_images#566]
I am stuck on this for quite a while now i have tried searching and trying stuff but i am getting nowhere. 
My setup is as follows:
### Host
linux Distro:  Archlinux
kernel version: 5.14.2
docker version: 20.10.8, build 3967b7d28e
nvidia driver version: 470.63.01-1
nvidia container toolkit version: 1.5.0-2 , cgroups disabled.
amd gpu driver: xf86-video-amdgpu 21.0.0-1
### Container
base image: ubuntu:18.04
command line : `docker run -it --rm --privileged --gpus all -e DISPLAY=$DISPLAY -e XAUTHORITY=~/.Xauthority --network host --volume /tmp/.X11-unix/:/tmp/.X11-unix --volume $XAUTHORITY:/root/.Xauthority gazebo:libgazebo9-bionic gazebo`
### Expected results
expected gazebo window to open with hardware acceleration, using privileged access.
### Actual results
On using `--privileged`:
```
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  2
  Serial number of failed request:  35
  Current serial number in output stream:  36 
```
Without `--privileged` and specifying graphic cards in `--device`  manually:
gazebo window opens up with hardware acceleration and works smoothly as expected.

### Detailed description
I was actually trying to run gazebo version 9 in a custom image which i had created using `ubuntu:18.04` as base image.  i referred to `gazebo:libgazebo9-bionic`,`nvidia/cuda:11.4.1-cudnn8-devel-ubuntu18.04` and `ros:melodic-desktop` while writing the dockerfile.  i even tried the same thing for gazebo 11 on  the same base image and got the same issue as above. Whereas the exactly similar setup for ubuntu foxy works smoothly. i really need to use privileged because i am going to be working on hardware for a lot of time. please help me on how should this be fixed. thanks alot

P.S. Other GUI applications (rviz,moveit,etc) are running without any issues. Im getting this issue with gazebo only.

**Comment by tfoote** [comment]
I cannot reproduce this problem. 

I ran 
`docker run --rm -it  --gpus all --privileged  -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1   -e XAUTHORITY=/tmp/.dockereuv4bwy8.xauth -v /tmp/.dockereuv4bwy8.xauth:/tmp/.dockereuv4bwy8.xauth   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /etc/localtime:/etc/localtime:ro  288977b4ce49 gazebo`

and

`docker run --rm -it  --gpus all  -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1   -e XAUTHORITY=/tmp/.docker7okgw7e4.xauth -v /tmp/.docker7okgw7e4.xauth:/tmp/.docker7okgw7e4.xauth   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /etc/localtime:/etc/localtime:ro  288977b4ce49 gazebo`

Both successfully 

I used [rocker](https://github.com/osrf/rocker) to generate the commands for my system. 

```
rocker --x11 --nvidia --privileged gazebo:libgazebo9-bionic gazebo
rocker --x11 --nvidia gazebo:libgazebo9-bionic gazebo
```
Since both came up successfully I don't think that there's an underlying issue with the image or executable. You may want to compare your command line options compared to the ones rocker generated.

**Comment by ruffsl** [comment]
Closing inactive issue.

**Comment by pbogaard** [comment]
@Aetherbase @ruffsl Ok found the solution: update Mesa from 20.0.8 to 22.0.2.

`sudo add-apt-repository ppa:kisak/kisak-mesa -y
sudo apt update
sudo apt upgrade -y`

To check the current Mesa version:

`sudo apt install mesa-utils
glxinfo | grep Mesa`

**Comment by Aetherbase** [comment]
@pbogaard saw your solution long later and tried it out, works like charm! thanks alot

**Comment by yamachaso** [comment]
I faced the same problem and it worked well with the solution. Thanks a lot!!

**Comment by FiorellaSibona** [comment]
@pbogaard Hi! I am currently trying to update Mesa but as of now the version does not seem to update correctly: even after the upgrade the version is still 20.0.8. I tried both to upgrade while building the image and from within the container but nothing works. Any idea on what could have changed since 2022?

**Comment by Decwest** [comment]
@FiorellaSibona 
Hi! I faced the exact same issue, but instead of adding `ppa:kisak/kisak-mesa`, I resolved it by adding `ppa:kisak/turtle`.

```shell
sudo add-apt-repository ppa:kisak/turtle
sudo apt update
sudo apt upgrade -y

sudo apt install mesa-utils
glxinfo | grep Mesa
```

While `ppa:kisak/kisak-mesa` does not support Bionic and has ceased updates, `ppa:kisak/turtle` seems to be within the support range and has been updated until 2023-03-09.
