### ISSUE TITLE
Key expiration reported in Docker library build

### ISSUE THREAD

**Issue by nuclearsandwich** [osrf/docker_images#607]
Initially reported as a [comment on another issue](https://github.com/docker-library/official-images/pull/11692#issuecomment-1016916777).

```
W: GPG error: http://packages.ros.org/ros2/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics info@osrfoundation.org

W: GPG error: http://packages.ros.org/ros/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics info@osrfoundation.org
```

@ruffsl do you know where those logs were excerpted from? I'm completely unable to reproduce the issue building ros/noetic/ubuntu/ros-base locally using the latest public focal image.

**Comment by mikaelarguedas** [comment]
https://github.com/docker-library/official-images/pull/11727#issuecomment-1019447572

**Comment by tfoote** [comment]
Thanks for the link @mikaelarguedas sounds like it's not a problem on our end closing. 

@nuclearsandwich I found the logs. They're github actions on the commits. They don't use the summaries for the PRs at the bottom, but you can get to them by clicking the red X on that commit in the PR timeline above.

**Comment by tfoote** [comment]
So after looking into this a bit. We think that the image is getting an old key from the keyserver from before our may expiration incident. To that end we should probably bake in the key or do a fetch directly of the asc file instead of relying on the keyserver infrastructure being up to date. 

Example line in our dockerfiles: https://github.com/osrf/docker_images/blob/d874d2d4cae47e0d9d11534c5d5b5d5682461aee/ros/galactic/ubuntu/focal/ros-core/Dockerfile#L22

**Comment by ruffsl** [comment]
From what was reported upstream here:

https://github.com/docker-library/official-images/pull/11917#issuecomment-1051051769

It seems they've since deprecated the practice of any DNS or transparent traffic hijacking of keyserver requests, and have now settled on recommending only the most reliable key servers:

https://github.com/docker-library/official-images/pull/11924

https://github.com/tianon/pgp-happy-eyeballs/pull/5
