### ISSUE TITLE
Retire images based on xenial, buster and bionic due to reaching EOL

### ISSUE THREAD

**Issue by tfoote** [osrf/docker_images#660]
Xenial has reached EOL and we should turn off our builds for them. 

We were pinged: https://github.com/docker-library/official-images/pull/13950#issuecomment-1412515624

Soon we will also EOL Bionic too for ros and gazebo builds

https://github.com/docker-library/official-images/pull/13950#issuecomment-1414346913

**Comment by mikaelarguedas** [comment]
I was waiting for Gazebo 9 to reach EOL, as it was announced [yesterday](https://community.gazebosim.org/t/gazebo-classic-9-officially-end-of-life/1773) so I [retired the gazebo 9 images](https://github.com/docker-library/official-images/pull/14013).

There is now only  the gazebo 11 bionic image that we will have to retire, at the end of may

**Comment by mikaelarguedas** [comment]
Last action item of this issue is retiring melodic builds. This is blocked pending melodic final sync to hit the snapshots repository.
Not sure we will be able to build the final image as the bionic base image was retired: https://github.com/docker-library/official-images/pull/14867#issuecomment-1593769545 https://github.com/docker-library/official-images/pull/14934#issuecomment-1608379237
