### ISSUE TITLE
gzclient Dockerfiles

### ISSUE THREAD

**Issue by bisraelsen** [osrf/docker_images#82]
Let me start with saying I'm new to Docker.

I see that there are Dockerfiles in this repo for gzclient, but I can't find those tags on Docker hub. I copied the Docker file for gzclient7 from this repo, and everything works, but I'm wondering if I should have been able to find it on Docker hub.

I have been able to find libgzclient, gzserver, and gzweb Docker files as well as gzserverX (what is that?), but not gzclient.

Any help would be appreciated.

**Comment by ruffsl** [comment]
The gzclient tag was intended for when gzserver and gzclient would eventually be separated into two different debian packages. This has not yet happened, although I think major refactoring is in the works for gazebo 9.

The idea of the tag was to layer the larger client dependencies on top of the learner gzserver tag, but as of know gzclient comes with gzserver debian. I haven't enabled the build for the gzclient tag on as it's not entirely relevant at the moment. Its just installing some additional display libraries that I think are perhaps not entirely necessary or are already installed.

gzserverX had good intentions but difficult to maintain effort to build and track the master branch of gazebo, so that users could quickly test out the current development version of gazebo. Perhaps now that there are catkin packages for gazebo, this might be easier to revisit, but is not on my current horizon.

**Comment by ruffsl** [comment]
Closing from inactivity, please feel free to reopen.
